name: Build Frontend App

on:
  push:
    branches: [ main ]   # Runs automatically when you push to main
  pull_request:          # Runs when a PR is opened
  workflow_dispatch:     # Allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Upload dist folder
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
